# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Cardna-iOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Cardna-iOS
pod 'Moya', '~> 15.0'
pod 'IQKeyboardManagerSwift'
pod 'SnapKit', '~> 5.0.0'
pod 'Kingfisher', '~> 7.0'
pod 'Then'
pod 'lottie-ios'

end
